### ISSUE TITLE
Google search api having issues or is there a change needed?

### ISSUE THREAD

**Issue by gyoza** [hubot-scripts/hubot-google-images#10]
No longer getting gifs when using animate... Not entirely sure why, is there something that has been changed or is the since depreciated search API now defunct? Thanks.

**Comment by louim** [comment]
What version are you using? Anything interesting in the Hubot logs?

**Comment by Sarkazein** [comment]
Just updated the script to try to fix this issue.  Still having the same results using the old API.  Don't have a CSE set up.

**Comment by gyoza** [comment]
I used the latest version available here.

**Comment by james-ingold** [comment]
+1 having the same issue here

**Comment by HaroldPutman** [comment]
The deprecated API results seem to not honor imgtype=animated anymore
```
https://ajax.googleapis.com/ajax/services/search/images?v=1.0&rsz=8&q=cute+kittens&safe=active&imgtype=animated
```
Gives the same results as without the imgtype defined. That parameter is listed as "experimental" in the [documentation](https://developers.google.com/image-search/v1/jsondevguide?hl=en) so maybe the experiment is over?

We have great success animating with the CSE version.

**Comment by gyoza** [comment]
@HaroldPutman  Any idea where to get the CSE ID? When I use the default google search engine it gives me errors.. Any tipts

**Comment by louim** [comment]
@gyoza Information on how to setup Google CSE is here: https://developers.google.com/custom-search/docs/tutorial/creatingcse

**Comment by gyoza** [comment]
I figured it out... it is because I did not have "images" turned on :) Thanks for the link though!

**Comment by gyoza** [comment]
Man, 100 queries a day is a huge drag :(

**Comment by gyoza** [comment]
You know a ghetto way to do this is to add the as_filetype=gif to the list and then deconstruct the top 10 results in question to see if they have more than one frame (aka a real gif) and post that image. ha... its super ghetto but if they decide to never "fix" this for us and we dont want to be limited to 100 queries a day it may be something worth looking into..

**Comment by Sarkazein** [comment]
Not a bad thought.  Heck, just restricting to .gif files would increase the odds of getting an animated image result.

**Comment by ryanbmilbourne** [comment]
+1 We're seeing the same issue.  

What's interesting is that we sometimes get a gif, sometimes not.  The gifs are  rare, but we're not getting only images when using `animate me`.

**Comment by HaroldPutman** [comment]
@gyoza that approach may not be so ghetto. The CSE version limits the results to gif and includes "AND animated" in the query. There's no other option for this in the new API. This works most of the time.

FWIW, we have a team of 40 developers and have not ever had more that 45 image queries in a day. But maybe we're not as fun as most people :smirk_cat:

**Comment by alehandrof** [comment]
Can someone furnish an example? I have created a Custom Search Engine and a project in the Developers Console, but I'm getting 404 errors from hubot.

**Comment by HaroldPutman** [comment]
Did you set the environment variables before starting hubot? Something like this
(obviously using your real ids and keys)
```
export HUBOT_GOOGLE_CSE_ID=0493...7K
export HUBOT_GOOGLE_CSE_KEY=GGP...bsX
```

**Comment by alehandrof** [comment]
@HaroldPutman OK, I was using a Project ID instead of the CSE Key. I can't find this value anywhere :-/

**Comment by HaroldPutman** [comment]
Find the key here: Visit https://code.google.com/apis/console select your project and then choose **Credentials** under **APIs & Auth**.

**Comment by alehandrof** [comment]
Got it :trophy:

@HaroldPutman: Thank you. Without your help I would still be looking.

**Comment by seeReadCode** [comment]
To clarify the steps a bit

1. Create a CSE via these [instructions](https://developers.google.com/custom-search/docs/tutorial/creatingcse).  I had to set a search criteria but then I removed it later. 
2. Turn on images in Edit Search Engine > Setup > Basic > Image Search
3. Get ID  in Edit Search Engine > Setup > Basic > Details (via [these instructions](https://support.google.com/customsearch/answer/2649143?hl=en))
4. Get key here https://code.google.com/apis/console
5. Update your conf (and your modules if necessary)
6. Test ```hubot animate me gravy```

![gravy](http://media.giphy.com/media/10F93TEHvKMgHm/giphy.gif)

Thanks all!

**Comment by jasonleibowitz** [comment]
I'm having trouble setting up the Google CSE. I've following the instructions provided [previously linked to](https://developers.google.com/custom-search/docs/tutorial/creatingcse), but when I search for "gravy" it only returns patent application data. Can someone help me ensure I have the right options selected for CSE (screenshot of CSE Control Panel below). The main question is what site should I specify to search through? (I assumed www.google.com). 

When I use the query URL in the browser [this](https://gist.github.com/jasonleibowitz/df784719a484487792ed) is the response I get. It is working, but not in the way this hubot extension expects. There's no ```res.statusCode``` returned, so hubot-google-images responds with a 400 error. 

Thanks for the help. 

<img width="954" alt="screen shot 2015-09-03 at 11 18 05 am" src="https://cloud.githubusercontent.com/assets/2746773/9662477/93bf2aee-522d-11e5-8b37-90ccdef45e2a.png">

![screen shot 2015-09-03 at 11 18 12 am](https://cloud.githubusercontent.com/assets/2746773/9662462/878b8f10-522d-11e5-905f-34974c5b5238.png)

![screen shot 2015-09-03 at 11 18 16 am](https://cloud.githubusercontent.com/assets/2746773/9662467/8eda1818-522d-11e5-8d7a-f5bf5a5e098e.png)

**Comment by alehandrof** [comment]
@jasonleibowitz I think you needed to add at least one site to create the search engine.

But then you should remove them and change the "Sites search" option:

<img width="629" alt="custom_search_-_basic" src="https://cloud.githubusercontent.com/assets/1588449/9663045/2bad5bc2-526b-11e5-9ec0-68b3a6d8075a.png">

(Or, at least, that has worked for me.)

**Comment by jasonleibowitz** [comment]
@alehandrof That was the answer. Thank you so much!

**Comment by danoc** [comment]
Worked for me as well. This was way too complicated.

**Comment by atomicframeworks** [comment]
Worked for me. Thank you everyone for the help!

**Comment by ryanbmilbourne** [comment]
I'm not sure if CSE is the best option, given the artificially low API request limit that Google is imposing.  Our team is more active with our hubot and we burned through our request limit in ~4 hours.  

I was able to add the `as_filetype` parameter to the deprecated API request and get GIFs back, but @gyoza 's method will be required to root out the single-frame GIFs.  It might be worth putting into the code-base if it means that this project can continue support limitless GIF getting via the deprecated API.

**Comment by liquidmetal** [comment]
I was able to get the giphy option working. Should I submit a pull request for this? Are there any reasons to not go with giphy?

**Comment by louim** [comment]
@liquidmetal if you can implement as an option, pull request are very welcome!

**Comment by danoc** [comment]
Is anyone else not a huge fan of Giphy's results? I've always found that `animate me` in Hubot is miles better than Slack's `/giphy` integration. Not sure why that is the case though.

**Comment by louim** [comment]
@danoc you're not alone. It's because giphy doesn't have access to the same amount of image that Google have. And they are often mislabeled. 

But having it as an option is better than nothing at all.

**Comment by danoc** [comment]
:+1:

**Comment by gyoza** [comment]
Here is another ghetto method that we've come up with..

We've setup 10 google search accounts and we've setup our hubot to restart every hour and switch to the next account...That gives you 1000 queries a day... That is *a lot*..  Another ghetto fab ghetto but requires no forking of the code and figuring image manipulation techniques etc..

**Comment by Sarkazein** [comment]
@gyoza Ohhh that's an interesting idea.  Would probably solve the issue for my team's needs.  I might look into setting up a rotation for the accounts so that Hubot doesn't need to be restarted, but otherwise I think that'll work wonderfully.

**Comment by liquidmetal** [comment]
@gyoza @Sarkazein I could be wrong - but that probably violates the T&C of using the API.

**Comment by Sarkazein** [comment]
Darn... should have thought of that.  Oh well, we'll have to see how far 100 per day gets us.

**Comment by HaroldPutman** [comment]
Fixed in version 0.2.2 with PR #12

**Comment by mbadura** [comment]
Hi what value should HUBOT_GOOGLE_SAFE_SEARCH get ? '0' , 'off', 'false' is not working

**Comment by HaroldPutman** [comment]
The value of HUBOT_GOOGLE_SAFE_SEARCH is assigned to the "safe" parameter
in the search request. If you are using the [CSE API](
https://developers.google.com/custom-search/json-api/v1/reference/cse/list)
it can have a value of "high", "medium", or "off". If you are using the
[deprecated API](https://developers.google.com/image-search/v1/jsondevguide)
it can have a value of "active", "moderate" or "off".

What makes you believe that "off" is not working?

**Comment by mbadura** [comment]
@HaroldPutman 
Thats my var config: 

http://creativecast.de/mba/cs-hodor_·_Settings___Heroku_1BF23C25.png

And when i'm testing with f.e nude girl query it end up with different result than on google images search (with safesearch off)

**Comment by HaroldPutman** [comment]
Make sure you are running the latest code. This is a relatively new feature
(v0.2.3). check node_modules/hubot-google-images/src/google-images.coffee
and make sure you find HUBOT_GOOGLE_SAFE_SEARCH referenced in there.

If that is not the issue check the configuration of your Custom Search
Engine.

I'm haven't tested this feature myself, but I assume it works for
@taviscaron who submitted the PR.

On Tue, Nov 10, 2015 at 9:53 AM, Marek Badura <notifications@github.com>
wrote:

> @HaroldPutman <https://github.com/HaroldPutman>
> Thats my var config:
>
> http://creativecast.de/mba/cs-hodor_·_Settings___Heroku_1BF23C25.png
>
> And when i'm testing with f.e nude girl query it end up with different
> result than on google images search (with safesearch off)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hubot-scripts/hubot-google-images/issues/10#issuecomment-155440834>
> .
>



-- 
*Harold PUTMAN*
Web Technology Specialist

*O*  +1 859 232 2839
*M*  +1 859 904 9735
harold.putman@lexmark.com <email@lexmark.com>

<http://www.lexmark.com/>
www.lexmark.com

**Comment by taviscaron** [comment]
Confirm this. `HUBOT_GOOGLE_SAFE_SEARCH=off` works for both CSE and deprecated API

**Comment by mbadura** [comment]
@HaroldPutman : yes i'm running latest code
```
  q =
      q: query,
      searchType:'image',
      safe: process.env.HUBOT_GOOGLE_SAFE_SEARCH || 'high',
```

Can you tell me more about CSE settings ? I can see in developers console that its working. I user "Browser API Key" , maybe here's the issue ?

**Comment by geraldarthur** [comment]
@HaroldPutman @alehandrof @jasonleibowitz

Followed your example above but I'm still getting an empty `body` object returned when making the request. The result is all requests default to this [line of code](https://github.com/hubot-scripts/hubot-google-images/blob/master/src/google-images.coffee#L98), aka "Oops. I had trouble searching..."

My `res.statusCode` is still 200 though, and i'm using the latest version.

**Comment by dmerrick** [comment]
I'm experiencing the same thing as @geraldarthur. I followed the instructions, but every time I run "image me", Hubot says `Oops. I had trouble searching 'foo'. Try later.`

**Comment by Pretorian** [comment]
i'm getting results 4fold and sometimes timeouts, key and id are good.
