### ISSUE TITLE
Animated results are hit or miss

### ISSUE THREAD

**Issue by HaroldPutman** [hubot-scripts/hubot-google-images#13]
If you say `animate me kittens` you might not get an actual animation. Google image search API does not seem to provide an equivalent to the "experimental" `imgtype=animated` neither in the deprecated image search API nor the Custom Search Engine API. The current makeshift approach is to tack "animated" on to the query. 

A better approach would be to use the giphy API. or some other reliable source of animated GIF's.

**Comment by mhemmings** [comment]
```animate``` never works for me now. Always returns jpg or png :(

**Comment by soehlert** [comment]
I also never get animations anymore at all.

**Comment by vwbusguy** [comment]
Same here - there's no more apparent .gif filtering

**Comment by welkerc** [comment]
I am seeing maybe 1 in 100 being gifs.

**Comment by HaroldPutman** [comment]
Fix is coming in PR #14

**Comment by soehlert** [comment]
I don't see this as a fix. I can get giphy working as an integration in slack already and it's horrible compared to google was.

**Comment by HaroldPutman** [comment]
I understand. Google has a way of doing this but they don't expose it in the public API. Unfortunately the feature we were using before was "experimental" and they dropped it. After we have it consistently showing animated Gif's let's open a new ticket saying the gifs are not any good. ;-)

**Comment by soehlert** [comment]
Fair enough. Thanks Harold.
