### ISSUE TITLE
CSE has a limited number of free searches

### ISSUE THREAD

**Issue by HaroldPutman** [hubot-scripts/hubot-google-images#17]
Allow multiple CSE ID's and rotate them so that you can use more free searches. This idea was brought up in #10 by @gyoza.

**Comment by louim** [comment]
I'm not sure it's legal to do this: 

https://developers.google.com/terms/?hl=en

> d. API Limitations Google sets and enforces limits on your use of the APIs (e.g. limiting the number of API requests that you may make or the number of users you may serve), in our sole discretion. You agree to, and will not attempt to circumvent, such limitations documented with each API. If you would like to use any API beyond these limits, you must obtain Google's express consent (and Google may decline such request or condition acceptance on your agreement to additional terms and/or charges for that use). To seek such approval, contact the relevant Google API team for information (e.g. by using the Google developers console).

**Comment by HaroldPutman** [comment]
Yes it looks like the quota is per API key and not per search engine instance. You might be able to technically justify something like this by requiring each user to provide their own API key, and limit each user to 100 queries, but that seems crazy. 

A better solution might be to provide an automatic fallback when you reach the limit to use the deprecated API.
