### ISSUE TITLE
Hubot responds twice for some reason

### ISSUE THREAD

**Issue by kobleistvan** [hubot-scripts/hubot-google-images#18]
Either if I use image me or animate me, it returns not 1, but 2 search results. Any idea why?

**Comment by kobleistvan** [comment]
Nevermind, bringing up hubot help showed me I have the commands duplicated for some reason :)

**Comment by technicalpickles** [comment]
Are you using the slack adapter? https://github.com/slackhq/hubot-slack/issues/210

**Comment by kobleistvan** [comment]
The adapter's good, I just accidentally duplicated the hubot-google-images entry in the external-scripts.js :)

**Comment by kobleistvan** [comment]
Thank you though!
