### ISSUE TITLE
mustachify.me DOWN

### ISSUE THREAD

**Issue by wizsilex** [hubot-scripts/hubot-google-images#28]
http://mustachify.me/ has been down å long time, please remove the mustache me function

**Comment by HaroldPutman** [comment]
#6 added the ability to host your own mustachify. I think what we should do is remove the default mustachify config and respond to mustache requests with a note about setting that up.
 
@afeld  has asked for help here [afeld/mustachio/#44](https://github.com/afeld/mustachio/issues/44), but I guess no one has stepped up to help.

**Comment by afeld** [comment]
https://github.com/afeld/mustachio/issues/48 is the even bigger blocker actually. And yes, I would still love help!
