### ISSUE TITLE
Image results appear twice.

### ISSUE THREAD

**Issue by perrygoy** [hubot-scripts/hubot-google-images#49]
For a few weeks now, possibly since a Slack update, hubot-google-images' results are displayed twice. The actual image URL isn't sent twice, the image is just displayed twice. I thought it was just an issue with Slack but no other integration is having any issues.

<img width="595" alt="double image" src="https://user-images.githubusercontent.com/27103725/75259035-fe42bf00-57ac-11ea-93f3-740b33b2abb1.png">
<img width="642" alt="collapsed" src="https://user-images.githubusercontent.com/27103725/75259032-fdaa2880-57ac-11ea-9ac5-e125bbbc80f8.png">

Expected Behavior:
* Image results are displayed one time.

Prereq(s):
* Must have hubot set up in a slack channel.
* Must have the hubot-google-images library installed and configured.

Steps to Reproduce:
* Say `hubot animate a puppy` in the room with hubot.
* Observe the image displays twice.

**Comment by perrygoy** [comment]
Added context, the double-image does not happen on the mobile Slack client, only on the desktop app and website. Maybe it *is* just a Slack issue.

**Comment by ashishthukral** [comment]
this should be a Slack issue, we also facing similar issue - https://www.reddit.com/r/Slack/comments/f9coux/hubot_apps_posting_image_links_show_images_twice/fj7x967?utm_source=share&utm_medium=web2x

**Comment by ashishthukral** [comment]
notified Slack team, they identified issue n will work on fix. no eta

**Comment by perrygoy** [comment]
Looks like Slack fixed its issue! Thanks for the raise, @ashishthukral!
